### PR TITLE
ContributingCode: Add note about webkit-patch format

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Review by kkinnunen-apple — APPROVED** [review]
I'd like to move the formatting implementation to git-webkit instead of webkit-patch.

**Comment by kkinnunen-apple** [comment]
Note: please submit with correct commit message, as described in the document you're modifying :)
Needs a bug entry and a normal business-as-usual description.

**Comment by rniwa** [comment]
> Is this workflow new? I don't see it applied in the current git log.

No, it's a long standing WebKit policy that the commit message follows a certain format.

**Comment by philn** [comment]
> > Is this workflow new? I don't see it applied in the current git log.
> 
> No, it's a long standing WebKit policy that the commit message follows a certain format.

Thanks, I'm aware of that already. But in this specific repo I don't see it strictly applied.

**Pull request merged**
