### PR TITLE
Subbranch

### PR DESCRIPTION
**Pull request by AtulRaghuvanshi73**
#31 Writing Documentation on Inserting and Removing DOM nodes.

I have written about some basic DOM manipluation methods

### CODE REVIEW

**Review by rniwa — CHANGES_REQUESTED** [review]
No, this is not the documentation we want. We want to describe how node insertions & removals are implemented in WebKit, not how to use them in JS.

**Comment by AtulRaghuvanshi73** [comment]
ok, I work on this and edit the PR

**Comment by AtulRaghuvanshi73** [comment]
@rniwa can you suggest some resources to get some more info about how insertion and removal of dom nodes is done in webkit

**Comment by rniwa** [comment]
> @rniwa can you suggest some resources to get some more info about how insertion and removal of dom nodes is done in webkit

There is no documentation or resources to speak of. This is why it's a to-do item. I need to find a time to write them down.

**Comment by AtulRaghuvanshi73** [comment]
I have made a couple of changes. If this is not how it should be done, it would be helpful someone gives some resources about how this should look it or what are the contents which are missing.

**Review by rniwa — CHANGES_REQUESTED** [review]
None of this content belongs to DOM section of the documentation. We need explanation of how things are implemented, not how JS API works. That belongs to MDN and such.

**Comment by AtulRaghuvanshi73** [comment]
Ok I'll work on this. For now I'll just remove the PR.

**Pull request closed without merging**
